name: toc_module
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.8.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  http: ^1.4.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  extended_wrap: ^0.1.5
  flutter_svg: ^2.2.0
  flutter_widget_from_html: ^0.15.1
  provider: ^6.1.5
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.4
  flutter_rating_bar: ^4.0.1
  device_info_plus: ^10.1.1
  dotted_decoration: ^2.0.0
  open_file_plus: ^3.4.1+1
  animated_flip_counter: ^0.3.4
  geolocator: ^13.0.4
  just_the_tooltip: ^0.0.12
  smooth_page_indicator: ^1.2.1
  igot_ui_components: ^0.1.0
  dropdown_button2: ^2.3.9
  circular_countdown_timer: ^0.2.3
  autocomplete_textfield: ^2.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  reorderables: ^0.6.0
  youtube_player_flutter: ^9.1.2
  flutter_inappwebview: 6.1.5
  share_plus: ^11.0.0
  pdfx: 2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
